# Generated by Django 5.2.8 on 2026-07-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='موجودی (ریال)'),
        ),
    ]
