# Generated by Django 5.2.8 on 2026-07-01 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=50, unique=True, verbose_name='کد پیگیری')),
                ('source_card', models.CharField(max_length=16, verbose_name='کارت مبدأ')),
                ('destination_card', models.CharField(max_length=16, verbose_name='کارت مقصد')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ (ریال)')),
                ('fee', models.DecimalField(decimal_places=0, default=5000, max_digits=15, verbose_name='کارمزد (ریال)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق'), ('reversed', 'برگشت خورده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('bank_reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع بانک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
